/** @file Generated by `generate-colors.cjs` script */

const colors = {
	'primary': '#1A77F2',
	'gray-0': '#FFFFFF',
	'gray-100': '#FBFBFB',
	'gray-300': '#E8E8EA',
	'gray-600': '#A5A3A9',
	'gray-1000': '#2B3037',
};

export default colors;
